alias python='python3'
alias pip='python3 -m pip'
alias update='sudo apt-get update'
alias upgrade='sudo apt-get upgrade'
alias watch_nv='watch -n 1 nvidia-smi'
alias view_history='less /var/log/apt/history.log'
alias rr='. ranger'
alias lh='ls -lh'
