- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- link:
    ~/.bashrc_share: bashrc/share
    ~/.config/ranger/rc.conf:
    ~/.gitconfig:
    ~/.inputrc:
    ~/.tmux_share.conf: tmux/share.conf
    ~/.tmux.conf: tmux/client.conf
    ~/.vim/coc-settings.json: vim/coc-settings.json
    ~/.vim/tabline.vim: vim/tabline.vim
    ~/.vimrc: vim/vimrc
    # files appending
    ~/.bashrc_append: bashrc/client
    ~/.profile_append: profile_append

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - [./append.sh, Appending symlinks for exisiting files]
